name: MEMCACHE
channels:
  - defaults
  - conda-forge
dependencies:
  - boto3=1.24.28
  - brotlipy=0.7.0
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - cffi=1.15.1
  - click=8.0.4
  - cryptography=38.0.1
  - dataclasses=0.8
  - idna=3.4
  - importlib-metadata=4.11.3
  - itsdangerous=2.0.1
  - jinja2=3.0.3
  - libcxx=14.0.6
  - libffi=3.3
  - markupsafe=2.1.1
  - ncurses=6.3
  - openssl=1.1.1s
  - pip=22.1.2
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.9.13
  - python-dateutil=2.8.2
  - readline=8.1.2
  - s3transfer=0.6.0
  - setuptools=63.4.1
  - six=1.16.0
  - sqlite=3.39.2
  - tk=8.6.12
  - tzdata=2022c
  - urllib3=1.26.12
  - wheel=0.37.1
  - xz=5.2.5
  - zipp=3.8.0
  - zlib=1.2.12
  - pip:
    - argcomplete==2.0.0
    - attrs==22.1.0
    - aws-sam-translator==1.53.0
    - aws-xray-sdk==2.10.0
    - botocore==1.27.89
    - cachelib==0.9.0
    - cfn-flip==1.3.0
    - cfn-lint==0.71.0
    - charset-normalizer==2.1.1
    - colorama==0.4.4
    - docker==6.0.1
    - docutils==0.16
    - durationpy==0.5
    - ec2-metadata==2.10.0
    - ecdsa==0.18.0
    - flask==2.2.2
    - flask-awscognito==1.3
    - flask-caching==2.0.1
    - flask-jwt-extended==4.4.4
    - flask-reuploaded==1.2.0
    - flask-wtf==1.0.1
    - graphql-core==3.2.3
    - hjson==3.1.0
    - jmespath==1.0.1
    - jschema-to-python==1.2.3
    - jsondiff==2.0.0
    - jsonpatch==1.32
    - jsonpickle==2.2.0
    - jsonpointer==2.3
    - jsonschema==3.2.0
    - junit-xml==1.9
    - kappa==0.6.0
    - moto==4.0.9
    - mysql-connector-python==8.0.30
    - networkx==2.8.8
    - openapi-schema-validator==0.2.3
    - openapi-spec-validator==0.4.0
    - packaging==21.3
    - pbr==5.11.0
    - placebo==0.9.0
    - protobuf==3.20.1
    - pyasn1==0.4.8
    - pyjwt==2.6.0
    - pyparsing==3.0.9
    - pyrsistent==0.19.2
    - python-jose==3.3.0
    - python-slugify==7.0.0
    - pytz==2022.6
    - pyyaml==5.4.1
    - requests==2.28.1
    - responses==0.22.0
    - rsa==4.7.2
    - sarif-om==1.0.4
    - sshpubkeys==3.3.1
    - text-unidecode==1.3
    - toml==0.10.2
    - tqdm==4.64.1
    - troposphere==4.2.0
    - types-toml==0.10.8
    - websocket-client==1.4.2
    - werkzeug==2.2.2
    - wrapt==1.14.1
    - wtforms==3.0.1
    - xmltodict==0.13.0
    - zappa==0.56.1
